server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:h2:mem:shop
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: sa
    password: