server:
  port: ${SERVER_PORT:8085}

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddp: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:shop
    driverClassName: org.h2.Driver
    username: sa
    password:
